version: '2'
  
# Usage example: https://github.com/stilliard/docker-pure-ftpd/wiki/Docker-stack-with-Wordpress-&-FTP

services:
#  ftpd_server:
#    image: stilliard/pure-ftpd:hardened
#    container_name: pure-ftpd
#    ports:
#      - "21:21"
#      - "30000-30009:30000-30009"
#    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
#        #- "/home/paolo/TELLme-Hub/geosk/static/tellme/prova_ftp:/home/ftpuser/"
#      - "/home/paolo/TELLme-Hub/tellme_datacall:/home/ftpuser/"
#        #- "/folder_on_disk/data:/home/username/"
#        #- "/folder_on_disk/passwd:/etc/pure-ftpd/passwd"
#      - "/home/paolo/TELLme-Hub/geosk/static/tellme/prova_ftp_passwd/:/etc/pure-ftpd/passwd"

## uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
##      - "/folder_on_disk/ssl:/etc/ssl/private/"
#    environment:
#      PUBLICHOST: "localhost"
#      FTP_USER_NAME: ftpuser
#      FTP_USER_PASS: mypass
#      FTP_USER_HOME: /home/ftpuser
#      FTP_PASSIVE_PORTS: "30000:30019"
## also for ssl/tls:
##      ADDED_FLAGS: "--tls=2"
#    restart: always

  gdal2:
    image: ptagliolato/tellme_datacall_preprocessing:1.0.0
    container_name: gdal
    volumes:
      - "/home/paolo/TELLme-Hub/tellme_datacall:/usr/src/app/"
    restart: 'no'
    command: tail -F anything

