version: '2'

services:
  gdal2:
    image: ptagliolato/tellme_datacall_importworkflow:1.0
    container_name: gdal2
    volumes:
      - "${ROOT_DATA_FOLDER}:/usr/src/app/tellme_datacall/"
    restart: 'no'
    command: tail -F anything

